### PR TITLE
autobuild: fix warnings due to cp command exit code

### PR DESCRIPTION
**Pull request by rm-medina**
- migrate app-templates to CMake module
- bring latest version of autobuild script in
- move conf.d/autobuild to root folder
- update autobuild script to fix warnings triggered by
  cp operation error.

Bug-AGL: SPEC-2164
Signed-off-by: Raquel Medina <raquel.medina@konsulko.com>

### CODE REVIEW

**Comment by kooltux** [comment]
Thanks Raquel. Can you also push a revision update in meta-agl/meta-agl-profile-core/recipes-apis/high-level-viwi-service/high-level-viwi-service.bb ?

**Comment by rm-medina** [comment]
thanks kooltux!

**Comment by rm-medina** [comment]
I'll update the revision update in meta-agl later today.

**Comment by kooltux** [comment]
Perfect. Thx!

**Pull request merged**
